// Axis guide/Axis temp folder/components/axis/AxisCallout.vue
<script setup lang="ts">
/**
 * AxisCallout Component
 *
 * A contextual feedback component for displaying important messages, tips,
 * warnings, or errors. Features an accent bar on the left for visual emphasis.
 * Based on Kairo design system patterns adapted for Axis.
 *
 * USAGE:
 * <AxisCallout>Default info message</AxisCallout>
 * <AxisCallout type="success" title="Success!">Operation completed.</AxisCallout>
 * <AxisCallout type="warning" dismissible @dismiss="handleDismiss">Warning message</AxisCallout>
 * <AxisCallout type="error" title="Error">
 *   Something went wrong.
 *   <template #actions>
 *     <AxisButton variant="ghost" size="sm">Retry</AxisButton>
 *   </template>
 * </AxisCallout>
 *
 * TYPES:
 * - info (default): Blue accent - general information, tips, guidance
 * - success: Green accent - confirmations, completed actions
 * - warning: Yellow/amber accent - cautions, important notices
 * - error: Red accent - errors, critical issues, destructive warnings
 *
 * FEATURES:
 * - Accent bar on left (8px width) for visual type identification
 * - Optional title for emphasis
 * - Dismissible with X button (disabled by default)
 * - Actions slot for buttons/links (Learn more, Retry, etc.)
 * - Custom icon support (default icons per type)
 *
 * ACCESSIBILITY:
 * - Uses role="alert" for error type, role="status" for others
 * - Dismiss button has aria-label
 * - Icons are aria-hidden
 */

import type { Component } from "vue";
import { CheckCircleIcon, ExclamationTriangleIcon, XCircleIcon, XMarkIcon } from "@heroicons/vue/24/outline";
import AxisInfoIcon from "./icons/AxisInfoIcon.vue";

interface Props {
  /** Callout type determines color scheme and default icon */
  type?: "info" | "success" | "warning" | "error";
  /** Optional title displayed above the body text */
  title?: string;
  /** Show dismiss (X) button - default false */
  dismissible?: boolean;
  /** Custom icon component (overrides default type icon) */
  icon?: Component | null;
  /** Hide the icon entirely */
  hideIcon?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  type: "info",
  title: undefined,
  dismissible: false,
  icon: undefined,
  hideIcon: false,
});

const emit = defineEmits<{
  (e: "dismiss"): void;
}>();

// Track visibility for dismissible callouts
const isVisible = ref(true);

// Default icons per type
const defaultIcons: Record<string, Component> = {
  info: AxisInfoIcon,
  success: CheckCircleIcon,
  warning: ExclamationTriangleIcon,
  error: XCircleIcon,
};

// Get the icon to display
const displayIcon = computed(() => {
  if (props.hideIcon) return null;
  if (props.icon !== undefined) return props.icon;
  return defaultIcons[props.type];
});

// Type-based color classes - with dark mode support
const typeClasses = computed(() => {
  const types = {
    info: {
      container: "bg-accent-1-50 dark:bg-accent-1-950 border-accent-1-200 dark:border-accent-1-800",
      bar: "bg-accent-1-500",
      icon: "text-accent-1-700 dark:text-accent-1-400",
      title: "text-accent-1-900 dark:text-accent-1-100",
      body: "text-accent-1-800 dark:text-accent-1-200",
    },
    success: {
      container: "bg-success-50 dark:bg-success-950 border-success-300 dark:border-success-700",
      bar: "bg-success-500",
      icon: "text-success-700 dark:text-success-400",
      title: "text-success-900 dark:text-success-100",
      body: "text-success-800 dark:text-success-200",
    },
    warning: {
      container: "bg-alert-50 dark:bg-alert-950 border-alert-300 dark:border-alert-700",
      bar: "bg-alert-500",
      icon: "text-alert-700 dark:text-alert-400",
      title: "text-alert-900 dark:text-alert-100",
      body: "text-alert-800 dark:text-alert-200",
    },
    error: {
      container: "bg-error-50 dark:bg-error-950 border-error-300 dark:border-error-700",
      bar: "bg-error-500",
      icon: "text-error-700 dark:text-error-400",
      title: "text-error-900 dark:text-error-100",
      body: "text-error-800 dark:text-error-200",
    },
  };
  return types[props.type];
});

// ARIA role based on type
const ariaRole = computed(() => {
  return props.type === "error" ? "alert" : "status";
});

// Handle dismiss
const handleDismiss = () => {
  isVisible.value = false;
  emit("dismiss");
};
</script>

<template>
  <div
    v-if="isVisible"
    :role="ariaRole"
    :class="[
      'relative flex overflow-hidden rounded-md border',
      typeClasses.container,
    ]"
  >
    <!-- Accent bar -->
    <div
      :class="[
        'absolute left-0 top-0 bottom-0 w-2 shrink-0',
        typeClasses.bar,
      ]"
      aria-hidden="true"
    />

    <!-- Content area -->
    <div class="flex flex-1 items-start gap-3 py-3 pl-5 pr-3">
      <!-- Icon - aligned to baseline of first text line -->
      <component
        :is="displayIcon"
        v-if="displayIcon"
        :class="['w-5 h-5 shrink-0', typeClasses.icon]"
        :style="{ marginTop: '1px' }"
        aria-hidden="true"
      />

      <!-- Text content -->
      <div class="flex-1 min-w-0">
        <!-- Title -->
        <p
          v-if="title"
          :class="['text-body-regular font-semibold', typeClasses.title]"
        >
          {{ title }}
        </p>

        <!-- Body text -->
        <div
          :class="[
            'text-body-regular',
            typeClasses.body,
            title ? 'mt-1' : '',
          ]"
        >
          <slot />
        </div>

        <!-- Actions slot -->
        <div v-if="$slots.actions" class="mt-3 flex items-center gap-2">
          <slot name="actions" />
        </div>
      </div>

      <!-- Dismiss button -->
      <button
        v-if="dismissible"
        type="button"
        :class="[
          'shrink-0 p-1 rounded transition-colors',
          'hover:bg-black/5 dark:hover:bg-white/10 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-1',
          typeClasses.icon,
        ]"
        aria-label="Dismiss"
        @click="handleDismiss"
      >
        <XMarkIcon class="w-4 h-4" aria-hidden="true" />
      </button>
    </div>
  </div>
</template>

// src/components/axis/AxisCallout.tsx
/**
 * AxisCallout Component (React/Next.js version)
 *
 * A contextual feedback component for displaying important messages, tips,
 * warnings, or errors. Features an accent bar on the left for visual emphasis.
 * Following Axis design system specifications.
 *
 * USAGE:
 * <AxisCallout type="info">This is an informational message</AxisCallout>
 * <AxisCallout type="success" title="Success!" dismissible onDismiss={() => {}}>
 *   Your changes have been saved.
 * </AxisCallout>
 * <AxisCallout type="error" title="Error">Something went wrong</AxisCallout>
 *
 * TYPES:
 * - info (default): Informational messages (blue accent)
 * - success: Success confirmations (green accent)
 * - alert: Warnings and cautions (yellow accent)
 * - error: Errors and critical issues (red accent)
 *
 * FEATURES:
 * - Accent bar on left (8px width) for visual type identification
 * - Optional title for emphasis
 * - Dismissible with X button (disabled by default)
 * - Custom icon support (default icons per type)
 *
 * ACCESSIBILITY:
 * - Uses appropriate ARIA roles
 * - Dismissible callouts are focusable
 * - Icons are aria-hidden
 */

'use client';

import React, { HTMLAttributes, ReactNode } from 'react';

type CalloutType = 'info' | 'success' | 'alert' | 'error';

export interface AxisCalloutProps extends HTMLAttributes<HTMLDivElement> {
  /** Callout type/severity */
  type?: CalloutType;
  /** Optional title */
  title?: string;
  /** Custom icon (overrides default type icon) */
  icon?: ReactNode;
  /** Hide the icon entirely */
  hideIcon?: boolean;
  /** Show dismiss button */
  dismissible?: boolean;
  /** Dismiss handler */
  onDismiss?: () => void;
  /** Content */
  children: ReactNode;
}

export function AxisCallout({
  type = 'info',
  title,
  icon: customIcon,
  hideIcon = false,
  dismissible = false,
  onDismiss,
  children,
  className = '',
  ...props
}: AxisCalloutProps) {
  // Type-specific configurations using defined color tokens
  // Colors available: 50, 100, 300, 500, 700, 900, 950
  const typeConfig = {
    info: {
      container: 'bg-accent-1-50 dark:bg-accent-1-950 border-accent-1-300 dark:border-accent-1-700',
      bar: 'bg-accent-1-500',
      icon: 'text-accent-1-700 dark:text-accent-1-300',
      title: 'text-accent-1-900 dark:text-accent-1-100',
      text: 'text-accent-1-700 dark:text-accent-1-300',
      button: 'text-accent-1-700 dark:text-accent-1-300 hover:text-accent-1-900 dark:hover:text-accent-1-100',
    },
    success: {
      container: 'bg-success-50 dark:bg-success-950 border-success-300 dark:border-success-700',
      bar: 'bg-success-500',
      icon: 'text-success-700 dark:text-success-300',
      title: 'text-success-900 dark:text-success-100',
      text: 'text-success-700 dark:text-success-300',
      button: 'text-success-700 dark:text-success-300 hover:text-success-900 dark:hover:text-success-100',
    },
    alert: {
      container: 'bg-alert-50 dark:bg-alert-950 border-alert-300 dark:border-alert-700',
      bar: 'bg-alert-500',
      icon: 'text-alert-700 dark:text-alert-300',
      title: 'text-alert-900 dark:text-alert-100',
      text: 'text-alert-700 dark:text-alert-300',
      button: 'text-alert-700 dark:text-alert-300 hover:text-alert-900 dark:hover:text-alert-100',
    },
    error: {
      container: 'bg-error-50 dark:bg-error-950 border-error-300 dark:border-error-700',
      bar: 'bg-error-500',
      icon: 'text-error-700 dark:text-error-300',
      title: 'text-error-900 dark:text-error-100',
      text: 'text-error-700 dark:text-error-300',
      button: 'text-error-700 dark:text-error-300 hover:text-error-900 dark:hover:text-error-100',
    },
  }[type];

  // Default icons for each type
  const defaultIcon = {
    info: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z" />
      </svg>
    ),
    success: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    ),
    alert: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
      </svg>
    ),
    error: (
      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
      </svg>
    ),
  }[type];

  const icon = customIcon || defaultIcon;

  const containerClasses = [
    'relative flex overflow-hidden rounded-md border',
    typeConfig.container,
    className,
  ].filter(Boolean).join(' ');

  const showIcon = !hideIcon && icon;

  return (
    <div
      role={type === 'error' ? 'alert' : 'status'}
      className={containerClasses}
      {...props}
    >
      {/* Accent bar on left */}
      <div
        className={`absolute left-0 top-0 bottom-0 w-2 shrink-0 ${typeConfig.bar}`}
        aria-hidden="true"
      />

      {/* Content area */}
      <div className="flex flex-1 items-start gap-3 py-3 pl-5 pr-3">
        {/* Icon */}
        {showIcon && (
          <div className={`shrink-0 mt-0.5 ${typeConfig.icon}`} aria-hidden="true">
            {icon}
          </div>
        )}

        {/* Text content */}
        <div className="flex-1 min-w-0">
          {title && (
            <p className={`text-body-regular font-semibold ${typeConfig.title}`}>
              {title}
            </p>
          )}
          <div className={`text-body-regular ${typeConfig.text} ${title ? 'mt-1' : ''}`}>
            {children}
          </div>
        </div>

        {/* Dismiss Button */}
        {dismissible && onDismiss && (
          <button
            type="button"
            onClick={onDismiss}
            className={`shrink-0 p-1 rounded transition-colors hover:bg-black/5 dark:hover:bg-white/10 ${typeConfig.icon}`}
            aria-label="Dismiss"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        )}
      </div>
    </div>
  );
}
